### ISSUE TITLE
Q35. What NFS option allows the root user to access NFS shares as the root user?

### ISSUE THREAD

**Issue by debugx** [Ebazhanov/linkedin-skill-assessments-quizzes#3729] opened 2022-05-25 06:00 UTC
The mistake in the Q35. What NFS option allows the root user to access NFS shares as the root user?
The correct answer is no_root_squash

**Comment by debugx** [comment] 2022-05-25 06:02
It's about linux-assessment.md

**Comment by 101br03k** [comment] 2022-05-27 13:23
@debugx i have made a new pull request, could you check it to see if its allright (#3734)
also it also contains another issue fix so dont mind that one.

**Comment by 101br03k** [comment] 2022-05-27 13:25
the issue is fixed in pull request #3734

**Comment by Ebazhanov** [comment] 2022-05-29 09:23
Great job guys! Thank you @debugx, @101br03k

**Closed by Ebazhanov** 2022-05-29 09:23 UTC
Labels: help wanted, good first issue
