### ISSUE TITLE
2 new questions in Microsoft-word test  

### ISSUE THREAD

**Issue by Adarsh275** [Ebazhanov/linkedin-skill-assessments-quizzes#5658] opened 2023-04-22 17:47 UTC
I'm submitting an ISSUE: please check bellow screenshot of new questions which I encountered during my test of microsoft-word 

- [ x ] New question{'s} 

![image](https://user-images.githubusercontent.com/93258651/233798905-e04a88df-e64b-48a2-af81-7a8d5d652d37.png)

![image](https://user-images.githubusercontent.com/93258651/233798927-dbf417ed-0916-4147-aafb-e4227f7b351b.png)

**Comment by payalpm** [comment] 2023-05-15 07:57
@Ebazhanov @Adarsh275 plz assign me this issue i solve this

**Comment by smashcoder** [comment] 2023-10-09 04:53
The Answer to the first question is paragraph and second question is [A,C]. This question is already their in the [microsoft-word-quiz.md](https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/blob/main/microsoft-word/microsoft-word-quiz.md). 

@Ebazhanov Please Close this issue as the problem is already solved

**Closed** 2023-10-09 05:22 UTC
Labels: help wanted, good first issue
