### ISSUE TITLE
JAVA Question no. 172  is incomplete

### ISSUE THREAD

**Issue by RitikKumarParvat** [Ebazhanov/linkedin-skill-assessments-quizzes#6672] opened 2023-10-22 17:47 UTC
I'm submitting an ISSUE: please check one with "x"

- [ ] New question{'s} 
- [ ] New assessment 
- [x] Missed questions/answers 
- [ ] Request for new quiz/answers/...
- [x] Documentation issue or request for ...
- [ ] ...

**Comment by RitikKumarParvat** [comment] 2023-10-22 17:48
"I have already fixed it. Could you please verify if it's working correctly now?"

**Comment by Priyanshuthapliyal2005** [comment] 2023-10-22 18:07
i alredy have fixed it in issue #6669 

@Ebazhanov Please review the changes in this pull request #6670 and consider merging. Thank you!

**Comment by Priyanshuthapliyal2005** [comment] 2023-10-22 18:48
sir @Ebazhanov 
this is the duplicate of the issue #6669 
just close this issue .

**Closed** 2023-10-22 18:50 UTC
Labels: hacktoberfest-accepted, hacktoberfest
